name: school
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 6.0.0+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  shared_preferences:
  equatable:
  get_it: ^8.0.3
  retrofit: '>=4.0.0 <5.0.0'
  flutter_svg:
  logger: any
  lazy_load_scrollview: ^1.3.0
  toastification: ^2.0.0
  flutter_animate: ^4.5.0
  go_router: ^14.1.0
  reactive_forms: ^17.0.1
  reactive_date_time_picker: ^4.0.0
  reactive_dropdown_search: ^5.0.5
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  gap: ^3.0.1
  syncfusion_flutter_charts: ^28.1.36
  percent_indicator: ^4.2.3
  timer_count_down: ^2.2.2
  dotted_border: ^2.1.0
  file_picker: ^8.1.4
  open_file: ^3.5.10
  flutter_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.5
  build_runner: '>=2.3.0 <4.0.0'

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: GolosText
      fonts:
        - asset: assets/fonts/GolosText-Black.ttf
        - asset: assets/fonts/GolosText-Bold.ttf
          weight: 700
        - asset: assets/fonts/GolosText-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/GolosText-Regular.ttf
          weight: 400
        - asset: assets/fonts/GolosText-Medium.ttf
          weight: 500
        - asset: assets/fonts/GolosText-SemiBold.ttf
          weight: 600

flutter_intl:
  enabled: true